# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networkinstitute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='networkinstitute.ProjectOwner'),
        ),
    ]
