# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkinstitute', '0002_auto_20160306_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('O', 'Operative'), ('A', 'Accepted'), ('D', 'Declined')], default='O', max_length=1),
        ),
    ]
