# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkinstitute', '0007_auto_20160309_0129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'default_permissions': ('add', 'change', 'delete'), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
