# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 11:55
from __future__ import unicode_literals

from django.db import migrations
import networkinstitute.models


class Migration(migrations.Migration):

    dependencies = [
        ('networkinstitute', '0009_auto_20160309_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='facebook',
            field=networkinstitute.models.NullableCharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='twitter',
            field=networkinstitute.models.NullableCharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
