# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkinstitute', '0010_auto_20160309_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='project',
        ),
        migrations.AddField(
            model_name='faculty',
            name='name',
            field=models.CharField(default='Faculty', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='faculties',
            field=models.ManyToManyField(related_name='faculties', to='networkinstitute.Faculty'),
        ),
    ]
