# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networkinstitute', '0011_auto_20160309_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(help_text='Please state the last date for applying to the project as yyyy-mm-dd'),
        ),
        migrations.AlterField(
            model_name='project',
            name='faculties',
            field=models.ManyToManyField(help_text='To select more faculties, hold ctrl for Windows or command for Mac', related_name='faculties', to='networkinstitute.Faculty'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkinstitute.ProjectOwner'),
        ),
    ]
