# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 01:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networkinstitute', '0016_auto_20160312_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='members',
        ),
        migrations.AddField(
            model_name='status',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
