# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkinstitute', '0017_auto_20160313_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('O', 'Operative'), ('A', 'Approved'), ('D', 'Declined')], default='O', max_length=1),
        ),
    ]
