# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('networkinstitute', '0018_auto_20160313_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('O', b'Operative'), ('A', b'Approved'), ('D', b'Declined')], default='O', max_length=1, validators=[djchoices.choices.ChoicesValidator({'A': b'Approved', 'D': b'Declined', 'O': b'Operative'})]),
        ),
    ]
