# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkinstitute', '0019_auto_20160313_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='twitter',
        ),
    ]
